import "./globals.css";
import { Inter } from "next/font/google";
import { prismaClient } from "@aaw/prisma";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cats = await prismaClient.category.findMany({
    where: {
      showInGallery: true,
    },
    orderBy: {
      disposition: "asc",
    },
  });

  return (
    <html lang="fr">
      <body className={inter.className}>
        <header>
          <ul>
            <li>
              <a href="/">Accueil</a>
            </li>
            <li>
              <a href="/galerie">Galerie</a>
            </li>
            {cats.map((c) => (
              <li key={c.id}>
                <a href={`/galerie/${c.slug}`}>{c.name}</a>
              </li>
            ))}
            <li>
              <a href="/realisation">Realisation</a>
            </li>
            <li>
              <a href="/manuscrit">Manuscrit</a>
            </li>
            <li>
              <a href="/contact">Contact</a>
            </li>
          </ul>
        </header>

        {children}
      </body>
    </html>
  );
}
