networks:
  aaw:

services:
  caddy:
    container_name: aaw_caddy
    image: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/caddy/data:/data
      - ./volumes/caddy/config:/config
      - ./certs:/data/certs
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - aaw

  database:
    container_name: aaw_database
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - aaw
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  storage:
    container_name: aaw_storage
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - ./storage/data:/data
    restart: unless-stopped
    networks:
      - aaw
