version: '3.6'
services:
  database:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - "@aaw"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}    
  
  storage:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage/data:/data
    restart: unless-stopped
    # TODO
    # MAYBE TO OLD ? https://thedatabaseme.de/2022/03/20/i-do-it-on-my-own-then-self-hosted-s3-object-storage-with-minio-and-docker/
    # https://hub.docker.com/r/minio/minio

networks:
  "@aaw":